SET search_path TO logistics;

CREATE TABLE orders_raw (
    type TEXT,
    days_for_shipping_real TEXT,
    days_for_shipment_scheduled TEXT,
    benefit_per_order TEXT,
    sales_per_customer TEXT,
    delivery_status TEXT,
    late_delivery_risk TEXT,
    category_id TEXT,
    category_name TEXT,
    customer_city TEXT,
    customer_country TEXT,
    customer_email TEXT,
    customer_fname TEXT,
    customer_id TEXT,
    customer_lname TEXT,
    customer_password TEXT,
    customer_segment TEXT,
    customer_state TEXT,
    customer_street TEXT,
    customer_zipcode TEXT,
    department_id TEXT,
    department_name TEXT,
    latitude TEXT,
    longitude TEXT,
    market TEXT,
    order_city TEXT,
    order_country TEXT,
    order_customer_id TEXT,
    order_date TEXT,
    order_id TEXT,
    order_item_cardprod_id TEXT,
    order_item_discount TEXT,
    order_item_discount_rate TEXT,
    order_item_id TEXT,
    order_item_product_price TEXT,
    order_item_profit_ratio TEXT,
    order_item_quantity TEXT,
    sales TEXT,
    order_item_total TEXT,
    order_profit_per_order TEXT,
    order_region TEXT,
    order_state TEXT,
    order_status TEXT,
    order_zipcode TEXT,
    product_card_id TEXT,
    product_category_id TEXT,
    product_description TEXT,
    product_image TEXT,
    product_name TEXT,
    product_price TEXT,
    product_status TEXT,
    shipping_date TEXT,
    shipping_mode TEXT
);
CREATE TABLE orders_cleaned (
    order_id INTEGER,
    order_date TIMESTAMP,
    customer_id INTEGER,
    customer_fname VARCHAR(50),
    customer_lname VARCHAR(50),
    product_name VARCHAR(255),
    category_name VARCHAR(100),
    market VARCHAR(50),
    order_country VARCHAR(100),
    order_region VARCHAR(100),
    sales NUMERIC(10,2),
    order_profit NUMERIC(10,2),
    quantity INTEGER,
    delivery_status VARCHAR(50),
    shipping_mode VARCHAR(50),
    late_delivery_risk INTEGER
);
INSERT INTO orders_cleaned
SELECT
    order_id::INTEGER,
    TO_TIMESTAMP(order_date,'MM/DD/YYYY HH24:MI'),
    customer_id::INTEGER,
    customer_fname,
    customer_lname,
    product_name,
    category_name,
    market,
    order_country,
    order_region,
    sales::NUMERIC(10,2),
    order_profit_per_order::NUMERIC(10,2),
    order_item_quantity::INTEGER,
    delivery_status,
    shipping_mode,
    late_delivery_risk::INTEGER
FROM orders_raw;